const mockData = {
  products: [
    {
      id: 1,
      nombre: "Coca-Cola",
      descripcion: "Refresco de cola con burbujas",
      id_categoria: "Refresecos",
      cantidad: 10,
      precio_compra: 50.0,
      fecha_entrada: "2024-05-01",
      caducidad: "2025-12-31",
      ubicacion: "Estante 1",
      unidad_medida: "litros",
      cantidad_medida: 2.5,
      codigo_barras: "1234567890001",
      eliminado: false,
    },
    {
      id: 2,
      nombre: "Pepsi",
      descripcion: "Refresco de cola",
      id_categoria: "Refresecos",
      cantidad: 5,
      precio_compra: 30.0,
      fecha_entrada: "2024-05-02",
      caducidad: "2025-11-30",
      ubicacion: "Estante 2",
      unidad_medida: "litros",
      cantidad_medida: 1.0,
      codigo_barras: "1234567890002",
      eliminado: false,
    },
    {
      id: 3,
      nombre: "Fanta Naranja",
      descripcion: "Refresco sabor naranja",
      id_categoria: "Refresecos",
      cantidad: 20,
      precio_compra: 80.0,
      fecha_entrada: "2024-05-03",
      caducidad: "2025-10-31",
      ubicacion: "Estante 3",
      unidad_medida: "litros",
      cantidad_medida: 10,
      codigo_barras: "1234567890003",
      eliminado: false,
    },
    {
      id: 4,
      nombre: "Sprite",
      descripcion: "Refresco sabor lima-limón",
      id_categoria: "Refresecos",
      cantidad: 15,
      precio_compra: 60.0,
      fecha_entrada: "2024-05-04",
      caducidad: "2025-09-30",
      ubicacion: "Estante 4",
      unidad_medida: "litros",
      cantidad_medida: 3.0,
      codigo_barras: "1234567890004",
      eliminado: false,
    },
    {
      id: 5,
      nombre: "Agua Mineral",
      descripcion: "Agua embotellada sin gas",
      id_categoria: 2,
      cantidad: 8,
      precio_compra: 40.0,
      fecha_entrada: "2024-05-05",
      caducidad: "2025-08-31",
      ubicacion: "Estante 5",
      unidad_medida: "litros",
      cantidad_medida: 2.0,
      codigo_barras: "1234567890005",
      eliminado: false,
    },
    {
      id: 6,
      nombre: "Red Bull",
      descripcion: "Bebida energética",
      id_categoria: 3,
      cantidad: 12,
      precio_compra: 70.0,
      fecha_entrada: "2024-05-06",
      caducidad: "2025-07-31",
      ubicacion: "Estante 6",
      unidad_medida: "unidades",
      cantidad_medida: 5,
      codigo_barras: "1234567890006",
      eliminado: false,
    },
    {
      id: 7,
      nombre: "Monster Energy",
      descripcion: "Bebida energética",
      id_categoria: 1,
      cantidad: 18,
      precio_compra: 90.0,
      fecha_entrada: "2024-05-07",
      caducidad: "2025-06-30",
      ubicacion: "Estante 7",
      unidad_medida: "unidades",
      cantidad_medida: 4.0,
      codigo_barras: "1234567890007",
      eliminado: false,
    },
    {
      id: 8,
      nombre: "Lipton Ice Tea",
      descripcion: "Té frío sabor limón",
      id_categoria: "Refresecos",
      cantidad: 7,
      precio_compra: 35.0,
      fecha_entrada: "2024-05-08",
      caducidad: "2025-05-31",
      ubicacion: "Estante 8",
      unidad_medida: "litros",
      cantidad_medida: 1.5,
      codigo_barras: "1234567890008",
      eliminado: false,
    },
    {
      id: 9,
      nombre: "Nestea",
      descripcion: "Té frío sabor durazno",
      id_categoria: "Refresecos",
      cantidad: 25,
      precio_compra: 100.0,
      fecha_entrada: "2024-05-09",
      caducidad: "2025-04-30",
      ubicacion: "Estante 9",
      unidad_medida: "litros",
      cantidad_medida: 12,
      codigo_barras: "1234567890009",
      eliminado: false,
    },
    {
      id: 10,
      nombre: "Aquarius",
      descripcion: "Bebida isotónica",
      id_categoria: "Refresecos",
      cantidad: 9,
      precio_compra: 55.0,
      fecha_entrada: "2024-05-10",
      caducidad: "2025-03-31",
      ubicacion: "Estante 10",
      unidad_medida: "litros",
      cantidad_medida: 2.2,
      codigo_barras: "1234567890010",
      eliminado: false,
    },
    {
      id: 11,
      nombre: "Powerade",
      descripcion: "Bebida deportiva",
      id_categoria: "Refresecos",
      cantidad: 14,
      precio_compra: 65.0,
      fecha_entrada: "2024-05-11",
      caducidad: "2025-02-28",
      ubicacion: "Estante 11",
      unidad_medida: "litros",
      cantidad_medida: 2.8,
      codigo_barras: "1234567890011",
      eliminado: false,
    },
    {
      id: 12,
      nombre: "Gatorade",
      descripcion: "Bebida deportiva",
      id_categoria: 3,
      cantidad: 6,
      precio_compra: 28.0,
      fecha_entrada: "2024-05-12",
      caducidad: "2025-01-31",
      ubicacion: "Estante 12",
      unidad_medida: "litros",
      cantidad_medida: 8,
      codigo_barras: "1234567890012",
      eliminado: false,
    },
    {
      id: 13,
      nombre: "Schweppes Tónica",
      descripcion: "Agua tónica",
      id_categoria: 1,
      cantidad: 11,
      precio_compra: 58.0,
      fecha_entrada: "2024-05-13",
      caducidad: "2024-12-31",
      ubicacion: "Estante 13",
      unidad_medida: "litros",
      cantidad_medida: 3.3,
      codigo_barras: "1234567890013",
      eliminado: false,
    },
    {
      id: 14,
      nombre: "Sprite Zero",
      descripcion: "Refresco sin azúcar",
      id_categoria: "Refresecos",
      cantidad: 13,
      precio_compra: 62.0,
      fecha_entrada: "2024-05-14",
      caducidad: "2024-11-30",
      ubicacion: "Estante 14",
      unidad_medida: "litros",
      cantidad_medida: 2.6,
      codigo_barras: "1234567890014",
      eliminado: false,
    },
    {
      id: 15,
      nombre: "Fuze Tea",
      descripcion: "Té frío sabor frutos rojos",
      id_categoria: "Refresecos",
      cantidad: 17,
      precio_compra: 75.0,
      fecha_entrada: "2024-05-15",
      caducidad: "2024-10-31",
      ubicacion: "Estante 15",
      unidad_medida: "litros",
      cantidad_medida: 9,
      codigo_barras: "1234567890015",
      eliminado: false,
    },
    {
      id: 16,
      nombre: "Agua con Gas",
      descripcion: "Agua mineral con gas",
      id_categoria: 1,
      cantidad: 16,
      precio_compra: 85.0,
      fecha_entrada: "2024-05-16",
      caducidad: "2024-09-30",
      ubicacion: "Estante 16",
      unidad_medida: "litros",
      cantidad_medida: 4.5,
      codigo_barras: "1234567890016",
      eliminado: false,
    },
    {
      id: 17,
      nombre: "Clamato",
      descripcion: "Bebida de tomate",
      id_categoria: "zumos",
      cantidad: 19,
      precio_compra: 95.0,
      fecha_entrada: "2024-05-17",
      caducidad: "2024-08-31",
      ubicacion: "Estante 17",
      unidad_medida: "litros",
      cantidad_medida: 3.1,
      codigo_barras: "1234567890017",
      eliminado: false,
    },
    {
      id: 18,
      nombre: "Jumex Naranja",
      descripcion: "Jugo de naranja",
      id_categoria: "zumos",
      cantidad: 21,
      precio_compra: 105.0,
      fecha_entrada: "2024-05-18",
      caducidad: "2024-07-31",
      ubicacion: "Estante 18",
      unidad_medida: "litros",
      cantidad_medida: 11,
      codigo_barras: "1234567890018",
      eliminado: false,
    },
    {
      id: 19,
      nombre: "Boing Mango",
      descripcion: "Bebida de mango",
      id_categoria: "zumos",
      cantidad: 22,
      precio_compra: 110.0,
      fecha_entrada: "2024-05-19",
      caducidad: "2024-06-30",
      ubicacion: "Estante 19",
      unidad_medida: "litros",
      cantidad_medida: 5.0,
      codigo_barras: "1234567890019",
      eliminado: false,
    },
    {
      id: 20,
      nombre: "Del Valle Manzana",
      descripcion: "Jugo de manzana",
      id_categoria: "zumos",
      cantidad: 24,
      precio_compra: 120.0,
      fecha_entrada: "2024-05-20",
      caducidad: "2024-05-31",
      ubicacion: "Estante 20",
      unidad_medida: "litros",
      cantidad_medida: 3.5,
      codigo_barras: "1234567890020",
      eliminado: false,
    },
  ],
  clients: [
    {
      id: 1,
      nombre: "Juan Pérez",
      direccion: "Calle Falsa 123, Madrid",
      telefono: "+34 600 123 456",
      correo: "juan.perez@email.com",
      documento: "12345678A",
      tipo_cliente: "Particular",
      anadido_por: "admin",
    },
    {
      id: 2,
      nombre: "María García",
      direccion: "Av. Principal 45, Barcelona",
      telefono: "+34 611 987 654",
      correo: "maria.garcia@email.com",
      documento: "87654321B",
      tipo_cliente: "Empresa",
      anadido_por: "soporte",
    },
    {
      id: 3,
      nombre: "Pedro López",
      direccion: "Plaza Mayor 10, Valencia",
      telefono: "+34 622 555 333",
      correo: "pedro.lopez@email.com",
      documento: "11223344C",
      tipo_cliente: "Particular",
      anadido_por: "admin",
    },
    {
      id: 4,
      nombre: "Ana Torres",
      direccion: "Calle Luna 8, Sevilla",
      telefono: "+34 633 444 222",
      correo: "ana.torres@email.com",
      documento: "44332211D",
      tipo_cliente: "Empresa",
      anadido_por: "ventas",
    },
  ],
  suppliers: [
    {
      id: 1,
      nombre: "Distribuciones Alimentarias S.A.",
      direccion: "Polígono Industrial Norte, Calle 5, Madrid",
      telefono: "+34 910 456 789",
      correo: "contacto@distribucionesalimentarias.com",
    },
    {
      id: 2,
      nombre: "Logística y Suministros García SL",
      direccion: "Calle Transporte 12, Barcelona",
      telefono: "+34 932 345 678",
      correo: "ventas@logisticagarcia.com",
    },
    {
      id: 3,
      nombre: "Suministros Médicos del Sur",
      direccion: "Av. de la Salud 101, Sevilla",
      telefono: "+34 955 321 654",
      correo: "info@suministrosmedicosur.com",
    },
    {
      id: 4,
      nombre: "Proveedora Industrial López",
      direccion: "Camino de las Herrerías 27, Zaragoza",
      telefono: "+34 976 654 321",
      correo: "clientes@proveedoralopez.com",
    },
  ],
};

export default mockData;
